// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	Country   string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type Video struct {
	ID           uuid.UUID
	Name         string
	S3Url        string
	ThumbnailUrl string
	Duration     int32
	Resolution   string
	Size         int32
	Progress     int32
	ViewCount    int32
	Owner        pgtype.UUID
	UploadedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type VideoCategory struct {
	VideoID     uuid.UUID
	CategoryTag string
}

type VideoLike struct {
	VideoID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}
